/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiemailmanager;
import javax.swing.*;
import java.io.*;
import java.util.*;
/**
 *
 * @author Sazib
 */
public class Dashbord extends javax.swing.JFrame {
    public static String pwd="";
    /**
     * Creates new form Dashbord
     */
    public Dashbord(String pwds) {
       pwd=pwds;
        initComponents();
        setButton(login01, "Email01.txt");
        setButton(login02, "Email02.txt");
        setButton(login03, "Email03.txt");
        setButton(login04, "Email04.txt");
        setButton(login05, "Email05.txt");
        setButton(login06, "Email06.txt");
        setButton(login07, "Email07.txt");
        setButton(login08, "Email08.txt");
        setButton(login09, "Email09.txt");
        setButton(login10, "Email10.txt");
        setButton(login11, "Email11.txt");
        setButton(login12, "Email12.txt");
        setButton(login13, "Email13.txt");
        
        
    }
    
    
    void setButton(JButton b, String path){
         try
        {
            File f = new File(path);
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            String text=scn.nextLine();

           b.setText(text);
               
            }else {
                b.setText("Login!!");
            }
            
            
            
      
        
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        showpwd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        login01 = new javax.swing.JButton();
        login02 = new javax.swing.JButton();
        login03 = new javax.swing.JButton();
        login04 = new javax.swing.JButton();
        login05 = new javax.swing.JButton();
        login06 = new javax.swing.JButton();
        login07 = new javax.swing.JButton();
        login11 = new javax.swing.JButton();
        login10 = new javax.swing.JButton();
        login09 = new javax.swing.JButton();
        login08 = new javax.swing.JButton();
        login12 = new javax.swing.JButton();
        login13 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        inbox01 = new javax.swing.JButton();
        inbox02 = new javax.swing.JButton();
        inbox03 = new javax.swing.JButton();
        inbox06 = new javax.swing.JButton();
        inbox05 = new javax.swing.JButton();
        inbox04 = new javax.swing.JButton();
        inbox09 = new javax.swing.JButton();
        inbox08 = new javax.swing.JButton();
        inbox07 = new javax.swing.JButton();
        inbox12 = new javax.swing.JButton();
        inbox11 = new javax.swing.JButton();
        inbox10 = new javax.swing.JButton();
        inbox13 = new javax.swing.JButton();

        jButton12.setText("Login!!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DashBoard");
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("DashBoard :");

        jButton1.setText("Change Access Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        showpwd.setText("See PW");
        showpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(showpwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showpwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Login To Your EMail"));

        login01.setText("Login!!");
        login01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login01ActionPerformed(evt);
            }
        });

        login02.setText("Login!!");
        login02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login02ActionPerformed(evt);
            }
        });

        login03.setText("Login!!");
        login03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login03ActionPerformed(evt);
            }
        });

        login04.setText("Login!!");
        login04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login04ActionPerformed(evt);
            }
        });

        login05.setText("Login!!");
        login05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login05ActionPerformed(evt);
            }
        });

        login06.setText("Login!!");
        login06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login06ActionPerformed(evt);
            }
        });

        login07.setText("Login!!");
        login07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login07ActionPerformed(evt);
            }
        });

        login11.setText("Login!!");
        login11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login11ActionPerformed(evt);
            }
        });

        login10.setText("Login!!");
        login10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login10ActionPerformed(evt);
            }
        });

        login09.setText("Login!!");
        login09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login09ActionPerformed(evt);
            }
        });

        login08.setText("Login!!");
        login08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login08ActionPerformed(evt);
            }
        });

        login12.setText("Login!!");
        login12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login12ActionPerformed(evt);
            }
        });

        login13.setText("Login!!");
        login13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login01, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
            .addComponent(login02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login06, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(login13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(login07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(login13)
                .addGap(13, 13, 13))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Inbox"));

        inbox01.setText("Inbox");
        inbox01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox01ActionPerformed(evt);
            }
        });

        inbox02.setText("Inbox");
        inbox02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox02ActionPerformed(evt);
            }
        });

        inbox03.setText("Inbox");
        inbox03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox03ActionPerformed(evt);
            }
        });

        inbox06.setText("Inbox");
        inbox06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox06ActionPerformed(evt);
            }
        });

        inbox05.setText("Inbox");
        inbox05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox05ActionPerformed(evt);
            }
        });

        inbox04.setText("Inbox");
        inbox04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox04ActionPerformed(evt);
            }
        });

        inbox09.setText("Inbox");
        inbox09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox09ActionPerformed(evt);
            }
        });

        inbox08.setText("Inbox");
        inbox08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox08ActionPerformed(evt);
            }
        });

        inbox07.setText("Inbox");
        inbox07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox07ActionPerformed(evt);
            }
        });

        inbox12.setText("Inbox");
        inbox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox12ActionPerformed(evt);
            }
        });

        inbox11.setText("Inbox");
        inbox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox11ActionPerformed(evt);
            }
        });

        inbox10.setText("Inbox");
        inbox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox10ActionPerformed(evt);
            }
        });

        inbox13.setText("Inbox");
        inbox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbox13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inbox01, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
            .addComponent(inbox02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inbox13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(inbox01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inbox02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(inbox03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inbox04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inbox05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inbox06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inbox07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inbox08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(inbox09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inbox10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inbox11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inbox12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inbox13)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null,"System.Closing");
        JOptionPane.showMessageDialog(null,"Email Sender Comming");
        System.exit(5);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          MultiEmailManager m1=new MultiEmailManager();
          
          m1.writerEmailpw("DoNotOpen.txt");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpwdActionPerformed
         MultiEmailManager m1=new MultiEmailManager();
        String pwd=m1.readerEmailpw("DoNotOpen.txt");
        JOptionPane.showMessageDialog(null, "YOUR PASSWORD IS : "+pwd);
    }//GEN-LAST:event_showpwdActionPerformed

    private void login01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login01ActionPerformed
        String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email01.txt", email, pw);
        login01.setText(email);
        
    }//GEN-LAST:event_login01ActionPerformed

    private void login02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login02ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email02.txt", email, pw);
        login02.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login02ActionPerformed

    private void login03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login03ActionPerformed
      String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email03.txt", email, pw);
        login03.setText(email);
    }//GEN-LAST:event_login03ActionPerformed

    private void login04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login04ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email04.txt", email, pw);
        login04.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login04ActionPerformed

    private void login05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login05ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email05.txt", email, pw);
        login05.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login05ActionPerformed

    private void login06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login06ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email06.txt", email, pw);
        login06.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login06ActionPerformed

    private void login07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login07ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email07.txt", email, pw);
        login07.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login07ActionPerformed

    private void login08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login08ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email08.txt", email, pw);
        login08.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login08ActionPerformed

    private void login09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login09ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email09.txt", email, pw);
        login09.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login09ActionPerformed

    private void login10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login10ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email10.txt", email, pw);
        login10.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login10ActionPerformed

    private void login11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login11ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email11.txt", email, pw);
        login11.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login11ActionPerformed

    private void login12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login12ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email12.txt", email, pw);
        login12.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login12ActionPerformed

    private void login13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login13ActionPerformed
String email=JOptionPane.showInputDialog("ENTER YOUR GMAIL");
        String pw=JOptionPane.showInputDialog("ENTER YOUR Password");
        MultiEmailManager m1=new MultiEmailManager();
        m1.writerEmailAcc("Email13.txt", email, pw);
        login13.setText(email);        // TODO add your handling code here:
    }//GEN-LAST:event_login13ActionPerformed

    private void inbox01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox01ActionPerformed
            try
        {
            File f = new File("Email01.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us01=scn.nextLine();
            pw01=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
            
            EmailDashboard01 o=new EmailDashboard01(us01,pw01);
            
            o.setVisible(true);
         // JOptionPane.showMessageDialog(null, us01+" p : "+pw01);
            
            
            //inbox part
             try {
            
            gmailInbox gmail = new gmailInbox();
            gmail.setUserPass(us01,pw01);
            gmail.connect();
            gmail.openFolder("INBOX");
            
            int totalMessages = gmail.getMessageCount();
            int newMessages = gmail.getNewMessageCount();
            
            System.out.println("Total messages = " + totalMessages);
            System.out.println("New messages = " + newMessages);
            System.out.println("-------------------------------");
            
            //gmail.printAllMessageEnvelopes();
            gmail.printAllMessages();
            
        } catch(Exception e) {
            e.printStackTrace();
            System.exit(-1);
        }
            
    }//GEN-LAST:event_inbox01ActionPerformed

    private void inbox02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox02ActionPerformed
  try
        {
            File f = new File("Email02.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us02=scn.nextLine();
            pw02=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        //  JOptionPane.showMessageDialog(null, us01+" p : "+pw02); 
          EmailDashboard01 o=new EmailDashboard01(us02,pw02);
            o.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_inbox02ActionPerformed

    private void inbox03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox03ActionPerformed
  try
        {
            File f = new File("Email03.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us03=scn.nextLine();
            pw03=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
   EmailDashboard01 o=new EmailDashboard01(us03,pw03);
            o.setVisible(true);
         // JOptionPane.showMessageDialog(null, us03+" p : "+pw03);        // TODO add your handling code here:
    }//GEN-LAST:event_inbox03ActionPerformed

    private void inbox05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox05ActionPerformed
 try
        {
            File f = new File("Email04.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us05=scn.nextLine();
            pw05=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
  EmailDashboard01 o=new EmailDashboard01(us05,pw05);
            o.setVisible(true);
         // JOptionPane.showMessageDialog(null, us05+" p : "+pw05);        // TODO add your handling code here:
    }//GEN-LAST:event_inbox05ActionPerformed

    private void inbox04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox04ActionPerformed
              try
        {
            File f = new File("Email05.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us04=scn.nextLine();
            pw04=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
               EmailDashboard01 o=new EmailDashboard01(us05,pw05);
            o.setVisible(true);
         // JOptionPane.showMessageDialog(null, us04+" p : "+pw04);
    
    }//GEN-LAST:event_inbox04ActionPerformed

    private void inbox06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox06ActionPerformed
 try
        {
            File f = new File("Email06.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us06=scn.nextLine();
            pw06=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
  EmailDashboard01 o=new EmailDashboard01(us06,pw06);
            o.setVisible(true);
        //  JOptionPane.showMessageDialog(null, us06+" p : "+pw06);        // TODO add your handling code here:
    }//GEN-LAST:event_inbox06ActionPerformed

    private void inbox07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox07ActionPerformed
 try
        {
            File f = new File("Email07.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us07=scn.nextLine();
            pw07=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
  EmailDashboard01 o=new EmailDashboard01(us07,pw07);
            o.setVisible(true);
        //  JOptionPane.showMessageDialog(null, us07+" p : "+pw07);        // TODO add your handling code here:
    }//GEN-LAST:event_inbox07ActionPerformed

    private void inbox08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox08ActionPerformed
 try
        {
            File f = new File("Email08.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us08=scn.nextLine();
            pw08=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
  EmailDashboard01 o=new EmailDashboard01(us08,pw08);
            o.setVisible(true);
         // JOptionPane.showMessageDialog(null, us08+" p : "+pw08);        // TODO add your handling code here:
    }//GEN-LAST:event_inbox08ActionPerformed

    private void inbox09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox09ActionPerformed
 try
        {
            File f = new File("Email09.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us09=scn.nextLine();
            pw09=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
  EmailDashboard01 o=new EmailDashboard01(us09,pw09);
            o.setVisible(true);
         // JOptionPane.showMessageDialog(null, us09+" p : "+pw09);        // TODO add your handling code here:
    }//GEN-LAST:event_inbox09ActionPerformed

    private void inbox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox10ActionPerformed
 try
        {
            File f = new File("Email10.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us10=scn.nextLine();
            pw10=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
  EmailDashboard01 o=new EmailDashboard01(us10,pw10);
            o.setVisible(true);
       //   JOptionPane.showMessageDialog(null, us10+" p : "+pw10);        // TODO add your handling code here:
    }//GEN-LAST:event_inbox10ActionPerformed

    private void inbox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox11ActionPerformed
 try
        {
            File f = new File("Email11.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us11=scn.nextLine();
            pw11=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
  EmailDashboard01 o=new EmailDashboard01(us11,pw11);
            o.setVisible(true);
       //   JOptionPane.showMessageDialog(null, us11+" p : "+pw11);        // TODO add your handling code here:
    }//GEN-LAST:event_inbox11ActionPerformed

    private void inbox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox12ActionPerformed
 try
        {
            File f = new File("Email12.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us12=scn.nextLine();
            pw12=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
  EmailDashboard01 o=new EmailDashboard01(us12,pw12);
            o.setVisible(true);
        //  JOptionPane.showMessageDialog(null, us12+" p : "+pw12);        // TODO add your handling code here:
    }//GEN-LAST:event_inbox12ActionPerformed

    private void inbox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbox13ActionPerformed
 try
        {
            File f = new File("Email13.txt");
            if(f.exists())
            {
               Scanner scn = new Scanner(f);
            us13=scn.nextLine();
            pw13=scn.nextLine();
               
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
  EmailDashboard01 o=new EmailDashboard01(us13,pw13);
           o.addListFromInbox();
            o.setVisible(true);
        //  JOptionPane.showMessageDialog(null, us13+" p : "+pw13);        // TODO add your handling code here:
            
            
            //inbox
            
//             try {
//            
//            gmailInbox gmail = new gmailInbox();
//            gmail.setUserPass(us13,pw13);
//            gmail.connect();
//            gmail.openFolder("INBOX");
//            
//            int totalMessages = gmail.getMessageCount();
//            int newMessages = gmail.getNewMessageCount();
//            
//            System.out.println("Total messages = " + totalMessages);
//            System.out.println("New messages = " + newMessages);
//            System.out.println("-------------------------------");
//            
//            gmail.printAllMessageEnvelopes();
//            gmail.printAllMessages();
//            
//        } catch(Exception e) {
//            e.printStackTrace();
//            System.exit(-1);
//        }
            
    }//GEN-LAST:event_inbox13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashbord(pwd).setVisible(true);
            }
        });
    }
    public String us01="";
    public String pw01="";
    public String us02="";
    public String pw02="";
    public String us03="";
    public String pw03="";
    public String us04="";
    public String pw04="";
    public String us05="";
    public String pw05="";
    public String us06="";
    public String pw06="";
    public String us07="";
    public String pw07="";
    public String us08="";
    public String pw08="";
    public String us09="";
    public String pw09="";
    public String us10="";
    public String pw10="";
    public String us11="";
    public String pw11="";
    public String us12="";
    public String pw12="";
    public String us13="";
    public String pw13="";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inbox01;
    private javax.swing.JButton inbox02;
    private javax.swing.JButton inbox03;
    private javax.swing.JButton inbox04;
    private javax.swing.JButton inbox05;
    private javax.swing.JButton inbox06;
    private javax.swing.JButton inbox07;
    private javax.swing.JButton inbox08;
    private javax.swing.JButton inbox09;
    private javax.swing.JButton inbox10;
    private javax.swing.JButton inbox11;
    private javax.swing.JButton inbox12;
    private javax.swing.JButton inbox13;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton login01;
    private javax.swing.JButton login02;
    private javax.swing.JButton login03;
    private javax.swing.JButton login04;
    private javax.swing.JButton login05;
    private javax.swing.JButton login06;
    private javax.swing.JButton login07;
    private javax.swing.JButton login08;
    private javax.swing.JButton login09;
    private javax.swing.JButton login10;
    private javax.swing.JButton login11;
    private javax.swing.JButton login12;
    private javax.swing.JButton login13;
    private javax.swing.JButton showpwd;
    // End of variables declaration//GEN-END:variables
}
