/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiemailmanager;


import java.awt.ScrollPane;
import java.io.File;
import java.util.Scanner;
import javax.mail.Message;
import javax.swing.DefaultListModel;
import javax.mail.*;
import java.io.*;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author Sazib
 */
public class EmailDashboard01 extends javax.swing.JFrame {
public String Username="";
 public String Password="";
 public int tom=0;
 public int nom=0;
public ArrayList frmz=new ArrayList();
public ArrayList subz=new ArrayList();
public ArrayList magz=new ArrayList();



 
 ListSelectionModel listSelectionModel;
    /**
     * Creates new form EmailDashboard01
     */
    public EmailDashboard01() {
        initComponents();
    }
 public EmailDashboard01(String u, String p) {
        Username=u;
        Password=p;
        initComponents();
       // nmtm();
         addListFromInbox();
     listed.addListSelectionListener(listSelectionListener);
     
    }
 
  
 
    DefaultListModel mod=new DefaultListModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollp = new javax.swing.JScrollPane();
        listed = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        exit_inbox_button = new javax.swing.JButton();
        TotalMsg = new javax.swing.JLabel();
        NewMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Email01-Dashboard");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email -Dashboard", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 102)));

        scrollp.setViewportView(listed);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Refresh Inbox");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Send EMail");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        exit_inbox_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit_inbox_button.setText("Exit Inbox");
        exit_inbox_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_inbox_buttonActionPerformed(evt);
            }
        });

        TotalMsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TotalMsg.setText("     ");

        NewMsg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewMsg.setText("     ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exit_inbox_button, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TotalMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollp, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollp))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339)
                .addComponent(exit_inbox_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    void nmtm() {
//        String tm="",nm="";
//        try {  
//               
//            gmailInbox gmail = new gmailInbox();
//            gmail.setUserPass(Username,Password);
//            gmail.connect();
//            gmail.openFolder("INBOX");
//            
//            int totalMessages = gmail.getMessageCount();
//            int newMessages = gmail.getNewMessageCount();
//           tm=""+totalMessages;
//           nm=""+newMessages;
//          
//           
//        } catch(Exception e) {
//            e.printStackTrace();
//            System.exit(-1);
//        }
//         NewMsg.setText("New Msgs : "+nm);
//         TotalMsg.setText("Total Msgs :"+tm);
//    }
    
    
    
    void addListFromInbox() {
        
           try {
            
            gmailInbox gmail = new gmailInbox();
            gmail.setUserPass(Username,Password);
            gmail.connect();
            gmail.openFolder("INBOX");
            
            int totalMessages = gmail.getMessageCount();
            int newMessages = gmail.getNewMessageCount();
            NewMsg.setText("New Msgs : "+newMessages);
         TotalMsg.setText("Total Msgs :"+totalMessages);
        //    gmail.printAllMessageEnvelopes();
            gmail.printAllMessages();
            frmz=gmail.getFrom();
            subz=gmail.getSubj();
            magz=gmail.getMesz();
            
            
            mod=gmail.ret();
             listed.setModel(mod);
              scrollp.setViewportView(listed);
        
            
        } catch(Exception e) {
            e.printStackTrace();
            System.exit(-1);
        }
        
        
        
    }
    ListSelectionListener listSelectionListener = new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent listSelectionEvent) {
           String fromm=" "+frmz.get(listSelectionEvent.getFirstIndex());
           String subjectt=" "+subz.get(listSelectionEvent.getFirstIndex());
           String msg=" "+magz.get(listSelectionEvent.getFirstIndex());
            
            Messegedialogue p=new Messegedialogue(fromm, subjectt,msg,Username,Password);
            p.setVisible(true);
            
        }
        
        
        
        
    };
   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       addListFromInbox();
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          EmailSender e=new EmailSender(Username, Password);
          e.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void exit_inbox_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_inbox_buttonActionPerformed
            dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exit_inbox_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailDashboard01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailDashboard01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailDashboard01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailDashboard01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailDashboard01().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NewMsg;
    private javax.swing.JLabel TotalMsg;
    private javax.swing.JButton exit_inbox_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JList listed;
    private javax.swing.JScrollPane scrollp;
    // End of variables declaration//GEN-END:variables

}
