/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiemailmanager;
import javax.swing.*;

/**
 *
 * @author Sazib
 */
public class SplashFrame extends javax.swing.JFrame {
public String  globalpwd="";    /**
     * Creates new form SplashFrame
     */
    public SplashFrame() {
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplashPanel = new javax.swing.JPanel();
        descriptionSplash = new javax.swing.JLabel();
        logoforSplash = new javax.swing.JLabel();
        PasswordSpalshDescription = new javax.swing.JLabel();
        sprt2spalsh = new javax.swing.JSeparator();
        sprt1spalsh = new javax.swing.JSeparator();
        SpashPwd = new javax.swing.JPasswordField();
        accessButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MultiEmailManager-by Sazib");
        setResizable(false);

        SplashPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Multi Email Manager", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial Black", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N

        descriptionSplash.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        descriptionSplash.setText("A Email Manager Which Helps You To Connect All Of Your EMails..");

        logoforSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiemailmanager/logo.png"))); // NOI18N
        logoforSplash.setText(" ");

        PasswordSpalshDescription.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        PasswordSpalshDescription.setText("Enter Your Security Password To Enter ");

        SpashPwd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        accessButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accessButton.setText("Access!!");
        accessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Hint : Defult Password IS : \"bracu\"");

        javax.swing.GroupLayout SplashPanelLayout = new javax.swing.GroupLayout(SplashPanel);
        SplashPanel.setLayout(SplashPanelLayout);
        SplashPanelLayout.setHorizontalGroup(
            SplashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SplashPanelLayout.createSequentialGroup()
                .addComponent(sprt1spalsh, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SplashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionSplash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpashPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(SplashPanelLayout.createSequentialGroup()
                .addGroup(SplashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SplashPanelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(logoforSplash))
                    .addGroup(SplashPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PasswordSpalshDescription)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sprt2spalsh, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(SplashPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SplashPanelLayout.setVerticalGroup(
            SplashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SplashPanelLayout.createSequentialGroup()
                .addComponent(descriptionSplash)
                .addGap(18, 18, 18)
                .addComponent(logoforSplash)
                .addGap(18, 18, 18)
                .addComponent(PasswordSpalshDescription)
                .addGap(17, 17, 17)
                .addComponent(sprt1spalsh, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpashPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sprt2spalsh, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SplashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SplashPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SplashPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessButtonActionPerformed
                  char []p=SpashPwd.getPassword();
                  MultiEmailManager m=new MultiEmailManager();
                  String pass=m.readerEmailpw("DoNotOpen.txt");
                  if(pass.equals("")) {
                      
                  }else {
                      globalpwd=pass;
                  }
                      
                  
                  String pas="";
                  for(int i=0;i<p.length;i++) {
                     pas=pas+p[i]; 
                  }
                  if(pass.equals(pas)) {
                      dispose();
                     Dashbord obj=new Dashbord(pass);
                      
                      obj.setVisible(true);
                  }else {
                      JOptionPane.showMessageDialog(null, "You have Provided Wrong Password");
                  }
                  
    }//GEN-LAST:event_accessButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordSpalshDescription;
    private javax.swing.JPasswordField SpashPwd;
    private javax.swing.JPanel SplashPanel;
    private javax.swing.JButton accessButton;
    private javax.swing.JLabel descriptionSplash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoforSplash;
    private javax.swing.JSeparator sprt1spalsh;
    private javax.swing.JSeparator sprt2spalsh;
    // End of variables declaration//GEN-END:variables
}
